### ISSUE TITLE
Dumb bot

### ISSUE THREAD

**Issue by PrincessNikki** [ACPlayGames/AirConBot#1]
Code doesn't work. Don't waste your time with this skid. He couldn't code to save his pathetic life.

**Comment by PrincessNikki** [comment]
I'll be rewriting this whole bot. Check my github for updates when the NEW code is written. This retard should keep to print spamming and time.sleep bullshit. Ultimate was his only good bot and he deleted it.

**Comment by PrincessNikki** [comment]
"discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'str' object has no attribute 'mentions" is but one of 389 errors in this skids code

**Comment by PrincessNikki** [comment]
Fyi @ACPlayGames, you're getting 0 credit for the updated version setting as 90% of your code is useless and doesn't work. So don't bitch in your pansy discord server like a little schoolgirl when i upload a better working version under my name.

**Comment by ACPlayGames** [comment]
Thank you for your rude yet accurate comments.
